name: hospital_room_management
description: Hospital Room Management (Room-focused) â€” Dart OOP
version: 0.1.0
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.0
